<?php
/**
 * Created by PhpStorm.
 * User: navyy
 * Date: 2017.07.21
 * Time: 9:56
 */
namespace Common\Model;

use Common\Model\BasicModel;

class CreateMessageModel extends BasicModel
{
    protected $autoCheckFields = false;

    protected $temp = [];

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        if(cookie('think_language') == 'en-us')
        {
            $this->temp = C('TEMP_EN');
        }
        else if(cookie('think_language') == 'ja-jp')
        {
            $this->temp = C('TEMP_JP');
        }
        else
        {
            $this->temp = C('TEMP_CN');
        }
    }
}